const CREATE_TRANSACTION_SUCCESS = "CREATE_TRANSACTION_SUCCESS";
const CREATE_TRANSACTION_FAILURE = "CREATE_TRANSACTION_FAILURE";


export {
  CREATE_TRANSACTION_SUCCESS,
  CREATE_TRANSACTION_FAILURE
}