const SINGLE_ACCOUNT_SUCCESS = "SINGLE_ACCOUNT_SUCCESS";
const SINGLE_ACCOUNT_FAILURE = "SINGLE_ACCOUNT_FAILURE";
const CREATE_ACCOUNT_SUCCESS = "CREATE_ACCOUNT_SUCCESS";
const CREATE_ACCOUNT_FAILURE = "CREATE_ACCOUNT_FAILURE";

export {
    SINGLE_ACCOUNT_SUCCESS,
    SINGLE_ACCOUNT_FAILURE,
    CREATE_ACCOUNT_SUCCESS,
    CREATE_ACCOUNT_FAILURE
}