const REGISTER_SUCCESS = "REGISTER_SUCCESS";
const REGISTER_FAILED = "REGISTER_FAILED"
const AUTHENTICATED_USER = "AUTHENTICATED_USER";
const NOT_AUTHENTICATED = "NOT_AUTHENTICATED";
const NO_TOKEN = "NO_TOKEN";
const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
const USER_PROFILE_FAILED = "USER_PROFILE_FAILED";
const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
const LOGOUT_FAILED = "LOGOUT_FAILED";


export {
    REGISTER_SUCCESS,
    REGISTER_FAILED,
    AUTHENTICATED_USER,
    NOT_AUTHENTICATED,
    NO_TOKEN,
    USER_PROFILE_SUCCESS,
    USER_PROFILE_FAILED,
    LOGOUT_SUCCESS,
    LOGOUT_FAILED
}